INSERT INTO characters (
    slug,
    name,
    race,
    class_type,
    role,
    personality,
    backstory,
    strengths,
    weakness,
    quote,
    image,
    vibe,
    difficulty
)
VALUES
(
    'astarion',
    'Astarion',
    'High Elf',
    'Rogue',
    'Stealth and Lockpicking',
    'Charming, sarcastic, dramatic, and dangerous.',
    'A vampire spawn attempting to escape the control of his former master.',
    'Excellent at stealth, traps, lockpicking, persuasion, and sneak attacks.',
    'Can be fragile during direct frontline combat.',
    'Careful, I bite.',
    '/src/assets/images/astarion.png',
    'Chaotic elegance',
    'Medium'
),
(
    'shadowheart',
    'Shadowheart',
    'High Half-Elf',
    'Cleric',
    'Healing and Support',
    'Secretive, loyal, sharp, and conflicted.',
    'A cleric with a mysterious past and a hidden connection to Shar.',
    'Strong healing, defensive magic, buffs, and support abilities.',
    'Her offensive damage can be limited early in the game.',
    'I still have a few tricks left.',
    '/src/assets/images/shadowheart.png',
    'Dark devotion',
    'Easy'
),
(
    'gale',
    'Gale',
    'Human',
    'Wizard',
    'Magic Damage',
    'Intelligent, dramatic, curious, and ambitious.',
    'A talented wizard carrying a dangerous magical condition.',
    'Powerful spells, area damage, and utility magic.',
    'Low health means that he often needs protection.',
    'A rough tempest I will raise.',
    '/src/assets/images/gale.png',
    'Arcane scholar',
    'Medium'
),
(
    'laezel',
    'Lae''zel',
    'Githyanki',
    'Fighter',
    'Frontline Damage',
    'Aggressive, disciplined, blunt, and fearless.',
    'A warrior raised under strict githyanki traditions.',
    'Strong melee attacks, heavy armor, and excellent survivability.',
    'Her blunt personality can make some social situations difficult.',
    'Enough waiting. We strike.',
    '/src/assets/images/laezel.png',
    'Warrior discipline',
    'Easy'
),
(
    'wyll',
    'Wyll',
    'Human',
    'Warlock',
    'Ranged Magic',
    'Heroic, honorable, charming, and conflicted.',
    'A monster hunter known as the Blade of Frontiers.',
    'Reliable ranged damage and strong charisma-based dialogue abilities.',
    'Has fewer spell slots than many other spellcasters.',
    'The Blade stands ready.',
    '/src/assets/images/wyll.png',
    'Hero with a secret',
    'Medium'
),
(
    'karlach',
    'Karlach',
    'Tiefling',
    'Barbarian',
    'Tank and Melee Damage',
    'Loud, warm-hearted, loyal, and explosive.',
    'A warrior with an infernal engine burning inside her chest.',
    'High damage, excellent health, and powerful frontline abilities.',
    'Has limited long-range combat options.',
    'Soldier!',
    '/src/assets/images/karlach.png',
    'Fire-hearted warrior',
    'Easy'
),
(
    'halsin',
    'Halsin',
    'Wood Elf',
    'Druid',
    'Nature Magic and Shapeshifting',
    'Wise, calm, protective, and grounded.',
    'A respected druid leader with a deep connection to nature.',
    'Flexible magic, healing abilities, and multiple Wild Shape forms.',
    'Can feel less specialized than some other companions.',
    'Nature will have its balance.',
    '/src/assets/images/halsin.png',
    'Guardian of nature',
    'Medium'
),
(
    'minthara',
    'Minthara',
    'Drow',
    'Paladin',
    'Melee and Divine Damage',
    'Commanding, ruthless, strategic, and intense.',
    'A powerful drow warrior with a dangerous past and strong convictions.',
    'Powerful smites, heavy armor, and strong melee combat abilities.',
    'Her recruitment depends heavily on the player''s story decisions.',
    'Weakness must be cut away.',
    '/src/assets/images/minthara.png',
    'Ruthless authority',
    'Hard'
),
(
    'jaheira',
    'Jaheira',
    'Half-Elf',
    'Druid',
    'Support and Nature Combat',
    'Wise, sarcastic, experienced, and brave.',
    'A veteran hero with many years of battle and leadership experience.',
    'Balanced support abilities, nature magic, and combat experience.',
    'She becomes available later in the game.',
    'The old ways still have teeth.',
    '/src/assets/images/jaheira.png',
    'Veteran protector',
    'Medium'
),
(
    'minsc',
    'Minsc',
    'Human',
    'Ranger',
    'Physical Damage',
    'Bold, funny, loyal, and unpredictable.',
    'A legendary ranger known for his courage and his hamster companion, Boo.',
    'Strong physical attacks and dependable ranged combat abilities.',
    'He joins the party very late in the game.',
    'Go for the eyes, Boo!',
    '/src/assets/images/minsc.png',
    'Chaotic heroism',
    'Medium'
),
(
    'the-dark-urge',
    'The Dark Urge',
    'Dragonborn',
    'Sorcerer',
    'Custom Origin and Magic Damage',
    'Mysterious, violent, haunted, and unpredictable.',
    'An origin character struggling to resist mysterious and violent impulses.',
    'Unique story content and powerful magical potential.',
    'Some story decisions can be morally difficult.',
    'Something inside me wants blood.',
    '/src/assets/images/dark-urge.png',
    'Dark mystery',
    'Hard'
),
(
    'tav',
    'Tav',
    'Custom',
    'Custom',
    'Player Choice',
    'Defined entirely by the player''s decisions.',
    'A fully customizable adventurer shaped by the player.',
    'Flexible race, class, abilities, personality, and story direction.',
    'Has less predefined history than the origin characters.',
    'The adventure begins with you.',
    '/src/assets/images/tav.png',
    'Limitless potential',
    'Varies'
);